server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

#spring-boot整合dubbo  
dubbo:
  scan:
    basePackages: com.jt #包扫描dubbo的service注解
  application:
    name: consumer-jt-web #提供者服务的名称
  registry: #连接zookeeper地址
    address: zookeeper://192.168.181.129:2181?backup=192.168.181.129:2182,192.168.181.129:2183  